In [1]:
import pandas as pd

In [2]:
s = pd.Series([10,20,30])

In [3]:
s

0    10
1    20
2    30
dtype: int64

In [4]:
d = pd.DataFrame({
    "name":["Ved","Taksh","Harsh"],
    "Age":[20,19,21],
    "batch":["B","A","A"]})

In [5]:
d

      name  Age batch
0  Ved   20     B
1    Taksh   19     A
2    Harsh   21     A

In [6]:
df = pd.read_csv("employee.csv")

### Data Selection

In [7]:
df["Department"].head()

0                     Sales
1    Research & Development
2    Research & Development
3    Research & Development
4    Research & Development
Name: Department, dtype: object

In [8]:
df[["Age", "Department", "MonthlyIncome"]].head()

   Age              Department  MonthlyIncome
0   41                   Sales           5993
1   49  Research & Development           5130
2   37  Research & Development           2090
3   33  Research & Development           2909
4   27  Research & Development           3468

### Data Filtering

In [9]:
df[df["Age"] > 40].head()

    Age Attrition  ... YearsSinceLastPromotion  YearsWithCurrManager
0    41       Yes  ...                       0                     5
1    49        No  ...                       1                     7
6    59        No  ...                       0                     0
18   53        No  ...                       3                     7
25   53        No  ...                       4                     8

[5 rows x 35 columns]

### Grouping

In [10]:
df.groupby("Department")["MonthlyIncome"].mean()

Department
Human Resources           6654.507937
Research & Development    6281.252862
Sales                     6959.172646
Name: MonthlyIncome, dtype: float64

### Aggregation

In [11]:
df.groupby("Department")["MonthlyIncome"].agg("mean")

Department
Human Resources           6654.507937
Research & Development    6281.252862
Sales                     6959.172646
Name: MonthlyIncome, dtype: float64